### ISSUE TITLE
Renaming a value in Thematic Values does not update in Character Value Comparison tab 

### ISSUE THREAD

**Issue by ryanreso1993** [Soyle-Productions/soyle-stories#76]
1. Given that the user has created a Value Web in the Character Value Comparison tab
And that the user has the Thematic Values tab open which lists the created character value
When the user renames the value in the Thematic Values tab

**Expected result**
Then the value name should be updated in the Character Value Comparison tab.

**Actual result**
The value rename does not update in the Character Value Comparison tab.

**Comment by b-camphart** [comment]
@ryanreso1993 please verify with new release

**Comment by ryanreso1993** [comment]
Bug doesn't seem to be fixed.

1. Create a new project
2. Create a character
3. Select Tools in the top toolbar
4. Select Themes
5. Create New Theme
6. Right-click new theme and select Compare Character Values
7. Add Character > Add created character
8. Add Value > Create New Value Web and name it
9. In the Themes tab, right click the created theme > Compare Values
10. Select your created Value Web. 
11. Select name of Value Web at the top and rename it

What I expect: The Value Web is renamed throughout the program

What actually happens: The Value Web name does not update within the Value Web in the Value Comparison tool nor does it update in the Compare Character Values tab

![image](https://user-images.githubusercontent.com/61167122/126047795-a218cfb3-f268-44b0-b33c-46162f821097.png)

![image](https://user-images.githubusercontent.com/61167122/126047800-8a919703-7485-422c-996b-b50e8ac37d09.png)

![image](https://user-images.githubusercontent.com/61167122/126047812-a26ef7bf-730a-4fa2-b12a-d2dab7b884c4.png)

**Comment by b-camphart** [comment]
I'm not sure I follow your example.  Which were you expecting to have updated?  It's difficult to follow because they're all similar names and I'm not sure which ones you're expecting to have be the same.  From what I can tell, it SEEMS like it's working as intended now, but there might be something I'm missing.

**Comment by ryanreso1993** [comment]
All values here should read "Love drunk" after the rename correction. But it did not update in two places:

![image](https://user-images.githubusercontent.com/61167122/127745037-df80a365-8dd8-472b-bd82-fb882d1da4f2.png)
![image](https://user-images.githubusercontent.com/61167122/127745047-fe22ffb2-9f80-4738-87cd-b7e3b017c87d.png)

**Comment by b-camphart** [comment]
Ok, the value web was successfully renamed (but still didn't update in the character comparison, which is a bug).  The opposition value won't be renamed because it's a separate thing.  We have a couple different options for handling this:

1. The first opposition value in every value web is always named the same thing as the value web.  You can't rename it.  All other opposition values can be renamed.
2. The first opposition value in the value web no longer has the same name as the value web in order to reduce confusion.  It will simply be titled "Opposition Value 1" and all subsequent opposition values will have the same name with incrementing numbers.  You can rename them as you like.
3. The first opposition value is named the same thing as the value web.  If you rename the value web, it will also be renamed.  However, if you rename the opposition value independently, it will no longer get renamed with the value web.  The question for this scenario is: should that be a permanent change, or should it re-sync if you rename the opposition value to have the same name as the value web (or vice versa)?

@ryanreso1993 thoughts?

**Comment by ryanreso1993** [comment]
Confirmed fixed.
